export default constants = {
    USER: "user",
    MALE: "male",
    FEMALE: "female",
    APP_NAME : 'Grocerie',
    ERROR_FIRST_NAME: 'Please enter first name!',
    ERROR_LAST_NAME: 'Please enter last name!',
    ERROR_FULL_NAME: 'Please enter full name!',
    ERROR_EMAIL: 'Please enter email id!',
    ERROR_FILTER: 'Please select atleast 1 filter!',
    ERROR_USERNAME: 'Please enter registered mobile number or email Id !',
    ERROR_MOBILE : 'Please enter 10 digit mobile number!',
    ERROR_EMAILV: 'Please enter valid email!',
    ERROR_PASSWORD: 'Please enter password!',
    ERROR_PAYMODE: 'Please select payment mode!',
    ERROR_USERID: 'Please enter email or mobile number!',
    ERROR_GENDER: 'Please select gender!',
    ERROR_ADDRESS: 'Please enter address!',
    ERROR_COUPON: 'Please enter coupon code!',
    ERROR_PIN: 'Please enter 6 dight pin code!',
    ERROR_AREA: 'Please enter area!',
    ERROR_CITY: 'Please enter city!',
    ERROR_STATE: 'Please enter state!',
    ERROR_ADDRESS: 'Please enter address!',
    MSG_DELETED : 'Deleted successfully!',
    TITLE_DELETE : 'Confirm',
    TITLE_ORDERLIST : 'Order List',
    TITLE_ORDER_SUCCESS : 'Order Placed',
    DES_DEL : 'Are you sure to delete this address?',
    DES_LOGOUT : 'Are you sure you want to logout?',
    TXT_FIRST_NAME : 'First Name',
    TXT_LAST_NAME : 'Last Name',
    TXT_FULL_NAME : 'Full Name',
    TXT_ADDRESS : 'Address',
    TXT_FREE : 'Free',
    TXT_COUPON_CODE : 'Enter Coupon Code',
    TXT_LANDMARK : 'Landmark',
    TXT_PIN : 'Pin Code',
    TXT_PROCEED_PAY : 'Proceed to Payment',
    TXT_ACC_DESC : 'Update your account details',
    TXT_ORDERS_DESC : 'Check your orders',
    TXT_ADDR_DESC : 'Manage your addresses',
    TXT_ADD : 'Add',
    TXT_DESC : 'Description',
    TXT_SIGNUP : 'Signup',
    TXT_FORGOT_PASS : 'Forgot Password?',
    TXT_CREATE_ACCOUNT :'Create your account',
    TXT_FORGOT_DESC : '',
    TXT_EMAIL : 'Email',
    TXT_AREA : 'Area',
    TXT_CITY : 'City',
    TXT_STATE : 'State',
    TXT_UPDATE : 'Update',
    FRM_CART : 'Cart',
    TXT_EMP_CART : 'Your Cart is empty',
    FRM_PRODUCTS : 'Products',
    TXT_EMP_PRODUCTS : 'No Product Found',
    FRM_ADDRESS : 'Address',
    TXT_EMP_ADDRESS : 'No Address Found',
    FRM_ORDERS : 'Orders',
    TXT_EMP_ORDERS : 'No Orders',
    TXT_DONT_ACCOUNT : 'Don\'nt have an account? ',
    TXT_LOGIN_TO : 'Log in to your account',
    TXT_PASSWORD : 'Password',
    TXT_MOBILE : 'Mobile No',
    TXT_GENDER : 'Gender',
    TXT_USERNAME : 'Username',
    TXT_REGISTER : 'Register',
    TXT_LOGIN : 'Login',
    TXT_TOTAL : 'Total: ',
    TXT_TOTAL_ITEMS : 'Total Items: ',
    TXT_ORDERNO : 'Order No: ',
    TXT_ORDERED : 'Ordered Items ',
    TXT_ITEMS : 'Items :',
    TXT_COST_DESC : 'Estimated cost(incl GST)',
    TXT_ADDTOCART : 'BUY',
    TXT_CHECKOUT : 'Checkout',
    TXT_SAVINGS : 'Savings',
    TXT_PROFILE : 'Profile',
    TXT_NET_AMT : 'Net Amount',
    TXT_RESET : 'Reset',
    TXT_NO_DATA : 'No data available!',
    TXT_ORDER_TOTAL : 'Order Total',
    TXT_PAYMENT_DETAILS : 'Payment Details',
    TXT_DELIVERED_ON : 'Delivered on',
    TXT_ADD_ADDRESS : 'Add New Address',
    TXT_DEL_ADDRESS : 'Delivery Address',
    TXT_CONTINUE : 'Continue',
    TXT_SUMMARY : 'Summary',
    DATE_SUFFIX : 'T00:00:00',
    TXT_PAY_OPTIONS : 'Payment Options',
    TXT_CONFIRM_ORDER : 'Confirm Order',
    TXT_CONFIRM_SUCCESS : 'Your order has been successfully placed!',
    TXT_ADD_CHANGE_ADDRESS : 'Add or change Address',
    TXT_ORDER_SUCCESS : 'Order successfully Placed',
    TXT_BACK_SHOPPING : 'Back to Shopping',
    TXT_THANKYOU : 'Thank you for \nyour Order',
    TXT_CAN_TRACK : 'You can track you order from the orders section',
    TXT_DONE:'Done',
    TXT_PAY:'Pay',
    TXT_CANCEL:'Cancel',
    IC_MATERIAL:'Material',
    IC_FONTISCO:'Fontisco',
    IC_IONIC:'Ionic',
    IC_OCT:'Oct',
    IC_FNT_AWESOME:'FontAwesome',
    TXT_PRODUCTS:'Products',
    SYMBOL_RUPEE : '\u20B9 ',
    PARAM_INDEX : 'Index',
    PARAM_NAV : 'Navigation',
    PARAM_USER : 'User',
    PARAM_ORDER : 'Order',
    PARAM_ADDRESS : 'Address',
    PARAM_ITEM : 'Item',
    PARAM_PRODUCT : 'Product',
    PARAM_MODE : 'Mode',
    MODE_EDIT : 'Edit',
    MODE_SELECT : 'Select',
    MODE_FIRST_ADD : 'First_Add',
    NAVIGATION : "",
    PLUS_SYMBOL :'+',
    TYPE_PLUS : 'Plus',
    TYPE_MINUS : 'Minus',
    TYPE_ADDCART : 'AddCart',
    TYPE_ADD : 'Add',
    TYPE_SELECT : 'Select',
    TYPE_DELETE : 'Delete',
    THEME_DEFAULT : 'Default',
    PREFS : 'Preferences',
    THEME_DARK : 'Dark',
    MINUS_SYMBOL: '-',
    TXT_CATEGORIES : 'Categories',
    TXT_APPLY : 'Apply',
    TXT_CHANGE : 'Change',
    TXT_APPLY_COUPON : 'Apply Coupon',
    TXT_COUPONS : 'Coupons',
    TXT_AVAIL_COUPONS : 'Available Coupons',
    TXT_SELECT_THEME : 'Select Theme',
    TXT_SEARCH_BYBRAND : 'Search By Brand',
    TXT_RECOMMENDATION : 'Recommendation',
    TXT_VIEWALL : 'VIEW ALL >',
    NO_INTERNET  : "Internet not available!",
    NO_INTERNET_REF  : "Internet not available . Swipe refresh to try again!"

}