export default constants = {
    USER: "user",
    MALE: "male",
    FEMALE: "female",
    ERROR_FIRST_NAME: 'Please enter first name!',
    ERROR_LAST_NAME: 'Please enter last name!',
    ERROR_FULL_NAME: 'Please enter full name!',
    ERROR_EMAIL: 'Please enter email id!',
    ERROR_MOBILE : 'Please enter 10 digit mobile number!',
    ERROR_EMAILV: 'Please enter valid email!',
    ERROR_PASSWORD: 'Please enter password!',
    ERROR_USERID: 'Please enter email or mobile number!',
    ERROR_GENDER: 'Please select gender!',
    ERROR_ADDRESS: 'Please enter address!',
    ERROR_PIN: 'Please enter 6 dight pin code!',
    ERROR_AREA: 'Please enter area!',
    ERROR_CITY: 'Please enter city!',
    ERROR_STATE: 'Please enter state!',
    ERROR_ADDRESS: 'Please enter address!',
    MSG_DELETED : 'Deleted successfully!',
    TITLE_DELETE : 'Confirm',
    TITLE_ORDER_SUCCESS : 'Order Placed',
    DES_DEL : 'Are you sure to delete this address?',
    TXT_FIRST_NAME : 'First Name',
    TXT_LAST_NAME : 'Last Name',
    TXT_FULL_NAME : 'Full Name',
    TXT_ADDRESS : 'Address',
    TXT_LANDMARK : 'Landmark',
    TXT_PIN : 'Pin Code',
    TXT_ADD : 'Add',
    TXT_SIGNUP : 'Signup',
    TXT_EMAIL : 'Email',
    TXT_AREA : 'Area',
    TXT_CITY : 'City',
    TXT_STATE : 'State',
    TXT_UPDATE : 'Update',
    TXT_PASSWORD : 'Password',
    TXT_MOBILE : 'Mobile No',
    TXT_GENDER : 'Gender',
    TXT_USERNAME : 'Username',
    TXT_REGISTER : 'Register',
    TXT_LOGIN : 'Login',
    TXT_TOTAL : 'Total :',
    TXT_ORDERNO : 'Order No :',
    TXT_ORDERNO : 'Order No :',
    TXT_ITEMS : 'Items :',
    TXT_ADDTOCART : 'ADD TO CART',
    TXT_CHECKOUT : 'Checkout',
    TXT_SAVINGS : 'Savings',
    TXT_PROFILE : 'Profile',
    TXT_NET_AMT : 'Net Amount',
    TXT_NO_DATA : 'No data available!',
    TXT_ORDER_TOTAL : 'Order Total',
    TXT_PAYMENT_DETAILS : 'Payment Details',
    TXT_DELIVERED_ON : 'Delivered on',
    TXT_ADD_ADDRESS : 'Add Address',
    TXT_CONTINUE : 'Continue',
    TXT_CONFIRM_ORDER : 'Confirm Order',
    TXT_CONFIRM_SUCCESS : 'Your order has been successfully placed!',
    TXT_ADD_CHANGE_ADDRESS : 'Add or change Address',
    TXT_ORDER_SUCCESS : 'Order successfully Placed',
    TXT_DONE:'Done',
    SYMBOL_RUPEE : '\u20B9 ',
    PARAM_INDEX : 'Index',
    PARAM_NAV : 'Navigation',
    PARAM_USER : 'User',
    PARAM_ORDER : 'Order',
    PARAM_ADDRESS : 'Address',
    PARAM_ITEM : 'Item',
    PARAM_PRODUCT : 'Product',
    PARAM_MODE : 'Mode',
    MODE_EDIT : 'Edit',
    MODE_SELECT : 'Select',
    MODE_FIRST_ADD : 'First_Add',
    NAVIGATION : "",
    PLUS_SYMBOL :'+',
    TYPE_PLUS : 'Plus',
    TYPE_MINUS : 'Minus',
    TYPE_ADDCART : 'AddCart',
    TYPE_DELETE : 'Delete',
    THEME_DEFAULT : 'Default',
    PREFS : 'Preferences',
    THEME_DARK : 'Dark',
    MINUS_SYMBOL: '-',
    TXT_CATEGORIES : 'Categories',
    TXT_SELECT_THEME : 'Select Theme',
    TXT_SEARCH_BYBRAND : 'Search By Brand',
    TXT_RECOMMENDATION : 'Recommendation',
    TXT_VIEWALL : 'VIEW ALL >',
    NO_INTERNET  : "Internet not available!x`"

}